---
version: "3.9"
networks:
  MacVlan_Network:
    driver: macvlan
    driver_opts:
        parent: enp3s0
    ipam:
        config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.0/24
services:
  gamesvrbot:
    image: gamesvrbot:latest
    container_name: gamesvrbot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - TOKEN=
      - SERVERMAC=
      - BROADCAST=
      - SERVER=
      - SERVERUSER=
    volumes:
      - /path/to/ssh/key:/usr/src/app/ssh.key
    ports:
      - 8080:8080
    networks:
      MacVlan_Network:
        ipv4_address: 192.168.1.x
    restart: unless-stopped